# Generated by Django 3.2.18 on 2023-05-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
